name: Push
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: npm ci
      - name: Test
        run: npm run test
      - name: Lint
        run: npm run lint
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Audit
        uses: treosh/lighthouse-ci-action@v2
        with:
          configPath: "./.github/config/local/lighthouserc.json"
          temporaryPublicStorage: true
          runs: 3
